"""
dashboard.py
============
Financial Organisation — Cyber Security Monitoring Dashboard
Task 4 | Data Science for Cyber Security

A real-time Plotly Dash application that monitors four security domains:
  1. Network Traffic
  2. Endpoints
  3. Data Backups
  4. Staff Readiness

The dashboard reads CSV files generated by generate_data.py and auto-refreshes
every 30 seconds to simulate a live data feed.

Usage:
    python Task4/dashboard.py
    Then open: http://127.0.0.1:8050
"""

# ── Standard library ──────────────────────────────────────────────────────────
import os
from datetime import datetime

# ── Third-party ───────────────────────────────────────────────────────────────
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import dash
import dash_bootstrap_components as dbc
from dash import dcc, html, Input, Output, callback

# ─────────────────────────────────────────────────────────────────────────────
# Constants & paths
# ─────────────────────────────────────────────────────────────────────────────

# Directory containing the CSV files (same folder as this script)
DATA_DIR = os.path.dirname(os.path.abspath(__file__))

# Paths to individual CSV files
NETWORK_CSV  = os.path.join(DATA_DIR, "network_traffic.csv")
ENDPOINT_CSV = os.path.join(DATA_DIR, "endpoints.csv")
BACKUP_CSV   = os.path.join(DATA_DIR, "backups.csv")
STAFF_CSV    = os.path.join(DATA_DIR, "staff_readiness.csv")

# Consistent colour palette used across the dashboard
COLOR_RED    = "#e74c3c"   # high-risk / anomaly
COLOR_AMBER  = "#f39c12"   # medium risk
COLOR_GREEN  = "#2ecc71"   # normal / safe
COLOR_BLUE   = "#3498db"   # neutral highlight
COLOR_BG     = "#1a1a2e"   # dark background
COLOR_CARD   = "#16213e"   # card background
COLOR_TEXT   = "#ecf0f1"   # primary text

# Map risk/status labels to colours for consistent coding across charts
RISK_COLOUR_MAP  = {"Low": COLOR_GREEN, "Medium": COLOR_AMBER, "High": COLOR_RED}
ANOMALY_COLOUR_MAP = {0: COLOR_GREEN, 1: COLOR_RED}


# ─────────────────────────────────────────────────────────────────────────────
# Data loading helpers
# ─────────────────────────────────────────────────────────────────────────────

def load_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load all four CSV datasets from disk.

    Called on initial load and every 30 seconds by the auto-refresh callback.

    Returns:
        Tuple of (network_df, endpoints_df, backups_df, staff_df).
    """
    network   = pd.read_csv(NETWORK_CSV,  parse_dates=["timestamp"])
    endpoints = pd.read_csv(ENDPOINT_CSV)
    backups   = pd.read_csv(BACKUP_CSV,   parse_dates=["backup_date"])
    staff     = pd.read_csv(STAFF_CSV)
    print(f"[dashboard] Data reloaded at {datetime.now().strftime('%H:%M:%S')}")
    return network, endpoints, backups, staff


# ─────────────────────────────────────────────────────────────────────────────
# KPI card builder
# ─────────────────────────────────────────────────────────────────────────────

def make_kpi_card(title: str, value: str, colour: str) -> dbc.Card:
    """Build a single KPI summary card with coloured value text.

    Args:
        title:  Short label displayed below the value.
        value:  Formatted metric value shown prominently.
        colour: Hex colour string for the value text.

    Returns:
        A dash_bootstrap_components Card component.
    """
    return dbc.Card(
        dbc.CardBody([
            html.H2(value, style={"color": colour, "fontWeight": "bold", "marginBottom": "4px"}),
            html.P(title, style={"color": COLOR_TEXT, "fontSize": "0.85rem", "marginBottom": 0}),
        ]),
        style={
            "backgroundColor": COLOR_CARD,
            "border": f"1px solid {colour}",
            "borderRadius": "8px",
            "textAlign": "center",
            "padding": "4px",
        }
    )


# ─────────────────────────────────────────────────────────────────────────────
# Chart builders
# ─────────────────────────────────────────────────────────────────────────────

def build_network_line(network: pd.DataFrame, protocol_filter: str) -> go.Figure:
    """Build Chart 1: Network Throughput line chart with anomaly highlights.

    Features a Plotly dropdown via the filter argument (protocol_filter)
    which is driven by the Dash callback. Anomalous data points are plotted
    as large red markers on top of the line.

    Args:
        network:         Full network traffic DataFrame.
        protocol_filter: Protocol string to filter by, or "All" for no filter.

    Returns:
        Plotly Figure object.
    """
    df = network.copy()
    if protocol_filter and protocol_filter != "All":
        df = df[df["protocol"] == protocol_filter]

    # Separate normal and anomaly rows for layered plotting
    normal  = df[df["anomaly_flag"] == 0]
    anomaly = df[df["anomaly_flag"] == 1]

    fig = go.Figure()

    # Main throughput line
    fig.add_trace(go.Scatter(
        x=df["timestamp"], y=df["throughput_mbps"],
        mode="lines+markers",
        name="Throughput",
        line=dict(color=COLOR_BLUE, width=2),
        marker=dict(size=5, color=COLOR_BLUE),
        hovertemplate="<b>%{x}</b><br>Throughput: %{y:.1f} Mbps<extra></extra>",
    ))

    # Anomaly overlay — large red markers
    if not anomaly.empty:
        fig.add_trace(go.Scatter(
            x=anomaly["timestamp"], y=anomaly["throughput_mbps"],
            mode="markers",
            name="Anomaly",
            marker=dict(size=14, color=COLOR_RED, symbol="x", line=dict(width=2, color="white")),
            hovertemplate="<b>ANOMALY</b><br>%{x}<br>Throughput: %{y:.1f} Mbps<extra></extra>",
        ))

    fig.update_layout(
        title=dict(text="Network Throughput Over Time", font=dict(color=COLOR_TEXT, size=16)),
        xaxis=dict(title="Timestamp", color=COLOR_TEXT, gridcolor="#2c2c44"),
        yaxis=dict(title="Throughput (Mbps)", color=COLOR_TEXT, gridcolor="#2c2c44"),
        paper_bgcolor=COLOR_CARD,
        plot_bgcolor=COLOR_BG,
        font=dict(color=COLOR_TEXT),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444"),
        margin=dict(l=50, r=20, t=50, b=50),
    )
    return fig


def build_geo_map(network: pd.DataFrame) -> go.Figure:
    """Build Chart 2: Geo-spatial scatter map of network traffic sources.

    Each point represents one network session. Colour encodes anomaly status
    (red = anomaly, green = normal) and size encodes throughput volume.

    Args:
        network: Full network traffic DataFrame.

    Returns:
        Plotly Figure object.
    """
    df = network.copy()
    df["anomaly_label"] = df["anomaly_flag"].map({0: "Normal", 1: "Anomaly"})
    df["colour"]        = df["anomaly_flag"].map({0: COLOR_GREEN, 1: COLOR_RED})

    fig = px.scatter_geo(
        df,
        lat="src_lat",
        lon="src_lon",
        color="anomaly_label",
        color_discrete_map={"Normal": COLOR_GREEN, "Anomaly": COLOR_RED},
        size="throughput_mbps",
        size_max=30,
        hover_data={
            "src_ip":          True,
            "protocol":        True,
            "throughput_mbps": ":.1f",
            "anomaly_label":   True,
            "src_lat":         False,
            "src_lon":         False,
        },
        projection="natural earth",
        title="Global Network Traffic Sources",
    )

    fig.update_layout(
        paper_bgcolor=COLOR_CARD,
        font=dict(color=COLOR_TEXT),
        title=dict(font=dict(color=COLOR_TEXT, size=16)),
        geo=dict(
            bgcolor=COLOR_BG,
            landcolor="#2c3e50",
            oceancolor="#1a1a2e",
            showocean=True,
            showland=True,
            showcountries=True,
            countrycolor="#444",
            framecolor="#444",
        ),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444", font=dict(color=COLOR_TEXT)),
        margin=dict(l=10, r=10, t=50, b=10),
    )
    return fig


def build_endpoint_bar(endpoints: pd.DataFrame) -> go.Figure:
    """Build Chart 3: Stacked bar chart of endpoint security status.

    Shows firewall, antivirus, and disk encryption status per hostname
    using traffic-light colour coding (red/amber/green).

    Args:
        endpoints: Endpoints DataFrame.

    Returns:
        Plotly Figure object.
    """
    df = endpoints.copy()

    # Encode each status as a numeric risk score for stacking height
    fw_colour  = df["firewall_status"].map({"Active": COLOR_GREEN, "Inactive": COLOR_RED})
    av_colour  = df["antivirus_status"].map({"Updated": COLOR_GREEN, "Outdated": COLOR_AMBER, "Missing": COLOR_RED})
    enc_colour = df["disk_encryption"].map({"Enabled": COLOR_GREEN, "Disabled": COLOR_RED})

    # One bar per metric per host, colour-coded by status
    fig = go.Figure()

    fw_colors  = df["firewall_status"].map({"Active": COLOR_GREEN, "Inactive": COLOR_RED}).tolist()
    av_colors  = df["antivirus_status"].map({"Updated": COLOR_GREEN, "Outdated": COLOR_AMBER, "Missing": COLOR_RED}).tolist()
    enc_colors = df["disk_encryption"].map({"Enabled": COLOR_GREEN, "Disabled": COLOR_RED}).tolist()

    fig.add_trace(go.Bar(
        name="Firewall",
        x=df["hostname"],
        y=[1] * len(df),
        marker_color=fw_colors,
        hovertext=df["firewall_status"],
        hovertemplate="<b>%{x}</b><br>Firewall: %{hovertext}<extra></extra>",
    ))
    fig.add_trace(go.Bar(
        name="Antivirus",
        x=df["hostname"],
        y=[1] * len(df),
        marker_color=av_colors,
        hovertext=df["antivirus_status"],
        hovertemplate="<b>%{x}</b><br>Antivirus: %{hovertext}<extra></extra>",
    ))
    fig.add_trace(go.Bar(
        name="Disk Encryption",
        x=df["hostname"],
        y=[1] * len(df),
        marker_color=enc_colors,
        hovertext=df["disk_encryption"],
        hovertemplate="<b>%{x}</b><br>Encryption: %{hovertext}<extra></extra>",
    ))

    fig.update_layout(
        barmode="stack",
        title=dict(text="Endpoint Security Status Overview", font=dict(color=COLOR_TEXT, size=16)),
        xaxis=dict(title="Hostname", color=COLOR_TEXT, gridcolor="#2c2c44"),
        yaxis=dict(title="Status Layers", color=COLOR_TEXT, gridcolor="#2c2c44", showticklabels=False),
        paper_bgcolor=COLOR_CARD,
        plot_bgcolor=COLOR_BG,
        font=dict(color=COLOR_TEXT),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444"),
        margin=dict(l=50, r=20, t=50, b=80),
    )
    return fig


def build_backup_gauge(backups: pd.DataFrame) -> go.Figure:
    """Build Chart 4a: Gauge chart showing average backup coverage.

    Colour zones: 0–60 red (critical), 60–80 amber (warning),
    80–100 green (good).

    Args:
        backups: Backups DataFrame.

    Returns:
        Plotly Figure object.
    """
    avg_coverage = round(backups["coverage_pct"].mean(), 1)

    fig = go.Figure(go.Indicator(
        mode="gauge+number+delta",
        value=avg_coverage,
        delta={"reference": 80, "valueformat": ".1f"},
        number={"suffix": "%", "font": {"color": COLOR_TEXT}},
        gauge={
            "axis":      {"range": [0, 100], "tickcolor": COLOR_TEXT},
            "bar":       {"color": COLOR_BLUE},
            "bgcolor":   COLOR_BG,
            "bordercolor": "#444",
            "steps": [
                {"range": [0,  60], "color": COLOR_RED},
                {"range": [60, 80], "color": COLOR_AMBER},
                {"range": [80, 100], "color": COLOR_GREEN},
            ],
            "threshold": {
                "line": {"color": "white", "width": 3},
                "thickness": 0.85,
                "value": 80,
            },
        },
        title={"text": "Average Backup Coverage", "font": {"color": COLOR_TEXT, "size": 14}},
    ))

    fig.update_layout(
        paper_bgcolor=COLOR_CARD,
        font=dict(color=COLOR_TEXT),
        margin=dict(l=30, r=30, t=60, b=20),
        height=280,
    )
    return fig


def build_backup_pie(backups: pd.DataFrame) -> go.Figure:
    """Build Chart 4b: Pie chart of backup validation results (Pass vs Fail).

    Args:
        backups: Backups DataFrame.

    Returns:
        Plotly Figure object.
    """
    counts = backups["validation_result"].value_counts().reset_index()
    counts.columns = ["result", "count"]
    colour_map = {"Pass": COLOR_GREEN, "Fail": COLOR_RED}

    fig = px.pie(
        counts,
        names="result",
        values="count",
        color="result",
        color_discrete_map=colour_map,
        title="Backup Validation Results",
        hole=0.35,
    )
    fig.update_traces(textfont_color=COLOR_TEXT)
    fig.update_layout(
        paper_bgcolor=COLOR_CARD,
        font=dict(color=COLOR_TEXT),
        title=dict(font=dict(color=COLOR_TEXT, size=14)),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444", font=dict(color=COLOR_TEXT)),
        margin=dict(l=20, r=20, t=60, b=20),
        height=280,
    )
    return fig


def build_staff_risk_bar(staff: pd.DataFrame) -> go.Figure:
    """Build Chart 5: Horizontal grouped bar chart of staff risk profiles by department.

    Shows the count of Low / Medium / High risk employees per department
    using green / amber / red colour coding.

    Args:
        staff: Staff readiness DataFrame.

    Returns:
        Plotly Figure object.
    """
    grouped = (
        staff.groupby(["department", "risk_profile"])
             .size()
             .reset_index(name="count")
    )

    fig = px.bar(
        grouped,
        x="count",
        y="department",
        color="risk_profile",
        color_discrete_map=RISK_COLOUR_MAP,
        orientation="h",
        barmode="group",
        title="Staff Risk Profile by Department",
        labels={"count": "Number of Staff", "department": "Department"},
        category_orders={"risk_profile": ["Low", "Medium", "High"]},
    )
    fig.update_layout(
        paper_bgcolor=COLOR_CARD,
        plot_bgcolor=COLOR_BG,
        font=dict(color=COLOR_TEXT),
        title=dict(font=dict(color=COLOR_TEXT, size=16)),
        xaxis=dict(color=COLOR_TEXT, gridcolor="#2c2c44"),
        yaxis=dict(color=COLOR_TEXT, gridcolor="#2c2c44"),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444"),
        margin=dict(l=140, r=20, t=50, b=50),
    )
    return fig


def build_staff_scatter(staff: pd.DataFrame) -> go.Figure:
    """Build Chart 6: Scatter plot of training compliance vs risk profile.

    X-axis: days since last training.
    Y-axis: training completion percentage.
    Point colour encodes risk profile; point size encodes pending trainings.
    Includes a range slider on the x-axis for interactive filtering.

    Args:
        staff: Staff readiness DataFrame.

    Returns:
        Plotly Figure object.
    """
    df = staff.copy()
    # Scale pending_trainings for visible size variation (min 8, max 30)
    df["marker_size"] = df["pending_trainings"].apply(lambda x: max(8, x * 5 + 8))

    fig = px.scatter(
        df,
        x="days_since_training",
        y="training_completion_pct",
        color="risk_profile",
        color_discrete_map=RISK_COLOUR_MAP,
        size="marker_size",
        size_max=30,
        hover_data={
            "employee_id":             True,
            "department":              True,
            "job_role":                True,
            "last_phishing_result":    True,
            "days_since_training":     True,
            "training_completion_pct": ":.1f",
            "marker_size":             False,
        },
        title="Training Compliance vs Risk Profile",
        labels={
            "days_since_training":     "Days Since Last Training",
            "training_completion_pct": "Training Completion (%)",
        },
        category_orders={"risk_profile": ["Low", "Medium", "High"]},
    )

    # Add a range slider on the x-axis
    fig.update_layout(
        xaxis=dict(
            rangeslider=dict(visible=True, bgcolor=COLOR_BG, bordercolor="#444"),
            color=COLOR_TEXT,
            gridcolor="#2c2c44",
        ),
        yaxis=dict(color=COLOR_TEXT, gridcolor="#2c2c44"),
        paper_bgcolor=COLOR_CARD,
        plot_bgcolor=COLOR_BG,
        font=dict(color=COLOR_TEXT),
        title=dict(font=dict(color=COLOR_TEXT, size=16)),
        legend=dict(bgcolor=COLOR_CARD, bordercolor="#444"),
        margin=dict(l=60, r=20, t=50, b=80),
    )
    return fig


# ─────────────────────────────────────────────────────────────────────────────
# KPI calculation helpers
# ─────────────────────────────────────────────────────────────────────────────

def calc_kpis(
    network: pd.DataFrame,
    endpoints: pd.DataFrame,
    backups: pd.DataFrame,
    staff: pd.DataFrame,
) -> dict:
    """Compute the four headline KPI values for the summary cards.

    Args:
        network:   Network traffic DataFrame.
        endpoints: Endpoints DataFrame.
        backups:   Backups DataFrame.
        staff:     Staff readiness DataFrame.

    Returns:
        Dictionary with keys: anomalies, endpoint_issues,
        backup_coverage, high_risk_staff.
    """
    return {
        "anomalies":        int(network["anomaly_flag"].sum()),
        "endpoint_issues":  int((endpoints["active_issues"] > 0).sum()),
        "backup_coverage":  round(backups["coverage_pct"].mean(), 1),
        "high_risk_staff":  int((staff["risk_profile"] == "High").sum()),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Dash app initialisation
# ─────────────────────────────────────────────────────────────────────────────

app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.CYBORG],
    title="Cyber Security Dashboard",
    suppress_callback_exceptions=True,
)

# ─────────────────────────────────────────────────────────────────────────────
# Layout
# ─────────────────────────────────────────────────────────────────────────────

# Global styles applied to the root container
GLOBAL_STYLE = {
    "backgroundColor": COLOR_BG,
    "minHeight": "100vh",
    "fontFamily": "'Segoe UI', 'Roboto', sans-serif",
    "padding": "0 20px 40px 20px",
}

SECTION_HEADER_STYLE = {
    "color": COLOR_BLUE,
    "fontWeight": "bold",
    "fontSize": "1.1rem",
    "letterSpacing": "0.08em",
    "textTransform": "uppercase",
    "borderBottom": f"1px solid {COLOR_BLUE}",
    "paddingBottom": "6px",
    "marginBottom": "16px",
    "marginTop": "30px",
}

CHART_CARD_STYLE = {
    "backgroundColor": COLOR_CARD,
    "border": "1px solid #2c2c44",
    "borderRadius": "10px",
    "padding": "16px",
    "marginBottom": "20px",
}


def build_layout() -> html.Div:
    """Construct the full Dash application layout.

    Returns:
        Root html.Div containing all layout components.
    """
    # Load data once at startup to get protocol list for the dropdown
    network, _, _, _ = load_data()
    protocols = ["All"] + sorted(network["protocol"].unique().tolist())

    return html.Div(style=GLOBAL_STYLE, children=[

        # ── Auto-refresh interval (30 s) ─────────────────────────────────────
        dcc.Interval(id="refresh-interval", interval=30_000, n_intervals=0),

        # ── Header bar ───────────────────────────────────────────────────────
        dbc.Row([
            dbc.Col([
                html.H1(
                    "🛡️ Financial Organisation — Cyber Security Dashboard",
                    style={"color": COLOR_TEXT, "fontWeight": "bold",
                           "fontSize": "1.6rem", "marginBottom": "2px"},
                ),
                html.P(
                    id="header-datetime",
                    style={"color": "#adb5bd", "fontSize": "0.85rem", "marginBottom": 0},
                ),
            ], width=12),
        ], style={"backgroundColor": "#0d0d1a", "padding": "20px 10px 12px 10px",
                  "marginLeft": "-20px", "marginRight": "-20px", "marginBottom": "20px",
                  "borderBottom": f"2px solid {COLOR_BLUE}"}),

        # ── KPI summary cards ────────────────────────────────────────────────
        dbc.Row(id="kpi-row", className="g-3"),

        # ════════════════════════════════════════════════════════════════════
        # SECTION 1 — Network Traffic
        # ════════════════════════════════════════════════════════════════════
        html.H4("1 — Network Traffic", style=SECTION_HEADER_STYLE),

        dbc.Row([
            # Protocol filter dropdown for Chart 1
            dbc.Col([
                html.Label("Filter by Protocol:", style={"color": "#adb5bd", "fontSize": "0.85rem"}),
                dcc.Dropdown(
                    id="protocol-dropdown",
                    options=[{"label": p, "value": p} for p in protocols],
                    value="All",
                    clearable=False,
                    style={"backgroundColor": "#2c2c44", "color": "#000", "fontSize": "0.9rem"},
                ),
            ], width=3, style={"marginBottom": "12px"}),
        ]),

        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-network-line"), style=CHART_CARD_STYLE),
                width=12,
            ),
        ]),
        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-geo-map"), style=CHART_CARD_STYLE),
                width=12,
            ),
        ]),

        # ════════════════════════════════════════════════════════════════════
        # SECTION 2 — Endpoints
        # ════════════════════════════════════════════════════════════════════
        html.H4("2 — Endpoints", style=SECTION_HEADER_STYLE),

        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-endpoint-bar"), style=CHART_CARD_STYLE),
                width=12,
            ),
        ]),

        # ════════════════════════════════════════════════════════════════════
        # SECTION 3 — Data Backups
        # ════════════════════════════════════════════════════════════════════
        html.H4("3 — Data Backups", style=SECTION_HEADER_STYLE),

        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-backup-gauge"), style=CHART_CARD_STYLE),
                width=6,
            ),
            dbc.Col(
                html.Div(dcc.Graph(id="chart-backup-pie"), style=CHART_CARD_STYLE),
                width=6,
            ),
        ]),

        # ════════════════════════════════════════════════════════════════════
        # SECTION 4 — Staff Readiness
        # ════════════════════════════════════════════════════════════════════
        html.H4("4 — Staff Readiness", style=SECTION_HEADER_STYLE),

        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-staff-risk-bar"), style=CHART_CARD_STYLE),
                width=12,
            ),
        ]),
        dbc.Row([
            dbc.Col(
                html.Div(dcc.Graph(id="chart-staff-scatter"), style=CHART_CARD_STYLE),
                width=12,
            ),
        ]),

        # ── Footer ───────────────────────────────────────────────────────────
        html.Hr(style={"borderColor": "#2c2c44"}),
        html.P(
            "Auto-refreshes every 30 seconds  |  Data: Task4/",
            style={"color": "#555", "fontSize": "0.75rem", "textAlign": "center"},
        ),
    ])


app.layout = build_layout


# ─────────────────────────────────────────────────────────────────────────────
# Callbacks
# ─────────────────────────────────────────────────────────────────────────────

@callback(
    # ── Header date/time ─────────────────────────────────────────────────────
    Output("header-datetime",    "children"),

    # ── KPI row ──────────────────────────────────────────────────────────────
    Output("kpi-row",            "children"),

    # ── Network charts ───────────────────────────────────────────────────────
    Output("chart-network-line", "figure"),
    Output("chart-geo-map",      "figure"),

    # ── Endpoint chart ───────────────────────────────────────────────────────
    Output("chart-endpoint-bar", "figure"),

    # ── Backup charts ────────────────────────────────────────────────────────
    Output("chart-backup-gauge", "figure"),
    Output("chart-backup-pie",   "figure"),

    # ── Staff charts ─────────────────────────────────────────────────────────
    Output("chart-staff-risk-bar", "figure"),
    Output("chart-staff-scatter",  "figure"),

    # ── Inputs ───────────────────────────────────────────────────────────────
    Input("refresh-interval",    "n_intervals"),
    Input("protocol-dropdown",   "value"),
)
def update_all(n_intervals: int, protocol_filter: str):
    """Master callback: reload data and rebuild all outputs.

    Triggered every 30 seconds by the dcc.Interval component or
    immediately when the protocol dropdown changes.

    Args:
        n_intervals:     Interval tick count (used to trigger data reload).
        protocol_filter: Selected protocol from the dropdown, or "All".

    Returns:
        Tuple of all Output values in declaration order.
    """
    # ── Reload data from disk ─────────────────────────────────────────────
    network, endpoints, backups, staff = load_data()

    # ── Header datetime ──────────────────────────────────────────────────
    now_str = f"Last refreshed: {datetime.now().strftime('%A, %d %B %Y  %H:%M:%S')}"

    # ── KPI cards ────────────────────────────────────────────────────────
    kpis = calc_kpis(network, endpoints, backups, staff)

    kpi_colour_anomalies = COLOR_RED   if kpis["anomalies"] > 3   else COLOR_AMBER if kpis["anomalies"] > 0 else COLOR_GREEN
    kpi_colour_endpoints = COLOR_RED   if kpis["endpoint_issues"] >= 5 else COLOR_AMBER if kpis["endpoint_issues"] > 0 else COLOR_GREEN
    kpi_colour_backup    = COLOR_GREEN if kpis["backup_coverage"] >= 80 else COLOR_AMBER if kpis["backup_coverage"] >= 60 else COLOR_RED
    kpi_colour_staff     = COLOR_RED   if kpis["high_risk_staff"] >= 3  else COLOR_AMBER if kpis["high_risk_staff"] > 0 else COLOR_GREEN

    kpi_cards = [
        dbc.Col(make_kpi_card("Total Anomalies Detected",  str(kpis["anomalies"]),        kpi_colour_anomalies), width=3),
        dbc.Col(make_kpi_card("Endpoints with Issues",     str(kpis["endpoint_issues"]),  kpi_colour_endpoints), width=3),
        dbc.Col(make_kpi_card("Avg Backup Coverage",       f"{kpis['backup_coverage']}%", kpi_colour_backup),    width=3),
        dbc.Col(make_kpi_card("Staff High Risk Count",     str(kpis["high_risk_staff"]),  kpi_colour_staff),     width=3),
    ]

    # ── Charts ───────────────────────────────────────────────────────────
    fig_network_line  = build_network_line(network, protocol_filter)
    fig_geo_map       = build_geo_map(network)
    fig_endpoint_bar  = build_endpoint_bar(endpoints)
    fig_backup_gauge  = build_backup_gauge(backups)
    fig_backup_pie    = build_backup_pie(backups)
    fig_staff_risk    = build_staff_risk_bar(staff)
    fig_staff_scatter = build_staff_scatter(staff)

    return (
        now_str,
        kpi_cards,
        fig_network_line,
        fig_geo_map,
        fig_endpoint_bar,
        fig_backup_gauge,
        fig_backup_pie,
        fig_staff_risk,
        fig_staff_scatter,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  Financial Organisation — Cyber Security Dashboard")
    print("  Starting server at http://127.0.0.1:8050")
    print("=" * 60)
    app.run(debug=False, host="127.0.0.1", port=8050)
